$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
#enter name for your environment
name: research-env
#image to be used
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
#conda file to customize image
conda_file: environment.yml
