name: env
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.11.7
  - pip:
      - mlflow
      - azureml-mlflow==1.53.0
      - azure-ai-ml==1.25.0
      - gymnasium
      - python-dotenv
      - jupyter
      - loguru
      - matplotlib
      - numpy
      - plotly
      - seaborn
      - tk
      - pydantic
